### ISSUE TITLE
Void variable lsp-error-list

### ISSUE THREAD

**Issue by fgabolde** [emacs-lsp/lsp-treemacs#12]
I can't use any of `lsp-treemacs-errors-list`, `lsp-treemacs-symbols`, or `lsp-treemacs-java-deps-list` because every time I do I get:

    autoload-do-load: Symbol’s value as variable is void: lsp-error-list

I am running the latest MELPA packages for all of lsp-mode, lsp-java and lsp-treemacs.

This is my LSP setup:

```
(use-package lsp-mode :ensure t)
(use-package hydra :ensure t)
(use-package company-lsp :ensure t :after lsp-mode)
(use-package lsp-ui :ensure t :after lsp-mode)
(use-package lsp-java :ensure t :after lsp-mode
  :config (add-hook 'java-mode-hook 'lsp))
(use-package lsp-treemacs :ensure t :after lsp-mode
  :commands lsp-treemacs-errors-list)

(use-package dap-mode
  :ensure t :after lsp-mode
  :config
  (dap-mode t)
  (dap-ui-mode t))

(use-package dap-java :after (lsp-java))
(add-hook 'java-mode-hook 'flycheck-mode)
```

**Comment by yyoncho** [comment]
I think that some of the packages  (probably treemacs was not downloaded successfully). Can you try after deleting your ~/.emacs/elpa dir? I am also unable to reproduce it with `emacs -q -l lsp-start-plain.el` where lsp-start-plain.el could be downloaded from https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ?

**Comment by fgabolde** [comment]
> I think that some of the packages (probably treemacs was not downloaded successfully). Can you try after deleting your ~/.emacs/elpa dir?

I will try.

> I am also unable to reproduce it with `emacs -q -l lsp-start-plain.el` where lsp-start-plain.el could be downloaded from https://github.com/emacs-lsp/lsp-mode/blob/master/scripts/lsp-start-plain.el ?

This seems to work just fine; since this setup doesn't have lombok support out of the box it is detecting plenty of errors :)

**Comment by fgabolde** [comment]
> I think that some of the packages (probably treemacs was not downloaded successfully). Can you try after deleting your ~/.emacs/elpa dir?

Yes, that was it. I cleaned up my init.el, regenerated `elpa/` from scratch, and the error tree works now. Thank you!
