### ISSUE TITLE
Treemacs will not expand

### ISSUE THREAD

**Issue by invisiblegaudi** [emacs-lsp/lsp-treemacs#137]
When I use the `lsp-treemacs-references`, the tab in the buffer below appears, with the count but it won't expand - when I tab over it, it just replicates across the minibuffer. Experiencing this on both OSX and Ubuntu. Using spacemacs flavour. Previous to this after an update, I noticed the tab/results design changed and it would replicate once only and then expand. This is an essential tool for refactoring, I am reduced to `helm-projectile-rg`-ing everything now to find the references :sob:

**Comment by RidaAyed** [comment]
Same here after updating arch linux

**Comment by yyoncho** [comment]
Can you try using treemacs from melpa stable? There is a breaking change in treemacs itself. (before that you may also need to wipe lsp-treemacs)

**Comment by timfel** [comment]
Throwing out my .emacs.d and starting fresh, but this time installing treemacs from melpa-stable didn't help. Afaics, they updated the version in melpa stable again just after the breaking change

**Comment by yyoncho** [comment]
Yep, you have to pit to the 2.11 commit. 

I am working on a fix, it will be available soon(I hope tomorrow)

**Comment by yyoncho** [comment]
It should be good now. The only thing that is broken is automatic expansion, I will fix it once we have the corresponding piece on treemacs side

**Comment by timcharper** [comment]
For packages which still refer to `lsp-treemacs-initialize`, what should they call now?

https://github.com/emacs-lsp/lsp-mssql/blob/88319a61a06e27fc1d3ea2e7b853ec1692b4c166/lsp-mssql.el#L607

https://github.com/emacs-lsp/lsp-mssql/issues/17

**Comment by yyoncho** [comment]
@timcharper they should be rewritten to use lsp-treemacs-render
