### ISSUE TITLE
Error: 'The connected server(s) does not support method textDocument/implementation'

### ISSUE THREAD

**Issue by nqminhuit** [emacs-lsp/lsp-treemacs#139]
Hello, 
(I'm not sure if this issue is from treemacs or lsp-treemacs)
After upgraded to latest treemacs (commit e4bb236bd5cd7c077c2207b33d2699485c405536) and LSP treemacs (commit: f7ae97560cfbc88e781a2d5b9253dace7175b918) I got the error:
```
lsp--send-request-async: The connected server(s) does not support method textDocument/implementation.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section
```
every time I invoked lsp functions.
I also try to upgrade my java language server to 1.15 (which is the latest, https://download.eclipse.org/jdtls/milestones/1.15.0/) still not  work, could you please help?

**Comment by yyoncho** [comment]
I tested with `M-x lsp-start-plain` and it seems to work fine.

**Comment by nqminhuit** [comment]
You're right, I use Doom emacs, and after cleanning the local workspace and re-import, lsp functions are back to normal, thank you for look into it!
