### ISSUE TITLE
Strange render in lsp-treemacs-symbols

### ISSUE THREAD

**Issue by PhilippeNoel1** [emacs-lsp/lsp-treemacs#14]
Hello,
I had a weird render when using lsp-treemacs-symbols like as show on the screenshot.
![Capture d’écran de 2019-09-14 15-54-53](https://user-images.githubusercontent.com/31954718/64909182-1cd66180-d709-11e9-9ea2-281cc1350b70.png)
Don't know if it is caused by treemacs or lsp-treemacs. I tried to disable my theme but it didn't change anything.

**Comment by yyoncho** [comment]
Can you elaborate what is the strange thing?

**Comment by PhilippeNoel1** [comment]
Sorry.
The problem is that each elements are separated with a blank line. Resulting in an extremely long buffer when I have a lot of elements. It's not a big interline, it's real blank lines.

**Comment by yyoncho** [comment]
It is treemacs setting, I will post it when I am on my dev pc.

**Comment by yyoncho** [comment]
Check `treemacs-space-between-root-nodes`

**Comment by PhilippeNoel1** [comment]
Thanks for all and sorry for your time.

**Comment by yyoncho** [comment]
@PhilippeNoel1 no worries.
