### ISSUE TITLE
lsp-treemacs-generic.el:102:2: Error: [Treemacs] :face parameter is mandatory

### ISSUE THREAD

**Issue by timfel** [emacs-lsp/lsp-treemacs#141]
I'm tried both treemacs 3.0 (pinned to melpa-stable) as well as 20220926.1903 from plain melpa, getting this error.

**Comment by timfel** [comment]
Simply adding a `:face 'default` at least fixes that for me, but I'm also still running into more issues with the new treemacs when debugging using dap-java.

**Comment by yyoncho** [comment]
Face was removed as param in latest treemacs.

**Comment by timfel** [comment]
Huh, that's odd. I see that change in the treemacs codebase now, but somehow it hasn't picked it up in the melpa version `20220926.1903` 🤔 

Ok, then something must be wrong on my end, sorry for the noise.
