### ISSUE TITLE
No thread selected when debugging

### ISSUE THREAD

**Issue by st1971** [emacs-lsp/lsp-treemacs#144]
when debugging (java / c / rust) getting `invalid-function lsp-treemacs-wcb-unless-killed` message, if starting via `lsp-start-plain` no thread is select when debugging and breakpoint is hit  (process does stop at a break point but it is not highlighted until the thread is selected manually) the thread has to be re-selected after each step over / into.

the `invalid-function lsp-treemacs-wcb-unless-killed` message seems to be related to the setting of `with-expanded-depth` on treemacs-initialize.

running emacs 28.1 with spacemacs

**Comment by st1971** [comment]
new version/build of treemacs (20221010.1959) landed on MELPA last night, this seems to resolve the `invalid-function lsp-treemacs-wcb-unless-killed` error.   the problem with thread selection on breakpoint is still there though

**Comment by hersheleh** [comment]
I am having the same issue when using dap-lldb. Do you know what lisp command corresponds to selecting the thread manually?

**Comment by yyoncho** [comment]
@hersheleh atm the  thread can be selected from dap-ui-sessions. I will take a look what is causing this problem.

**Comment by yyoncho** [comment]
@kiennq is adding `when` here https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-mode.el#L1923 was really needed? Seems like it might cause more regressions like that. Can we revert that change if it wasn't needed?

**Comment by kiennq** [comment]
@yyoncho Fix here https://github.com/emacs-lsp/lsp-mode/pull/3763

**Comment by st1971** [comment]
@yyoncho Many thanks for this all working for me now
