### ISSUE TITLE
symbol order reshuffles on focus changes

### ISSUE THREAD

**Issue by dsvensson** [emacs-lsp/lsp-treemacs#15]
For example focus changes causes the list of symbols to be reordered, but also navigating around in the source code. It would be nice to have it sorted alphabetically.

**Comment by yyoncho** [comment]
Agreed. The plan is to add different kinds of sortings(e. g. by name, by type, by position in file).

**Comment by yyoncho** [comment]
proposed fix at: https://github.com/emacs-lsp/lsp-treemacs/pull/27
