### ISSUE TITLE
defvar: Symbol’s function definition is void: treemacs-get-icon-value

### ISSUE THREAD

**Issue by mgallego** [emacs-lsp/lsp-treemacs#22]
When I try to execute lsp-treemacs always return the same error:

defvar: Symbol’s function definition is void: treemacs-get-icon-value

**Comment by yyoncho** [comment]
Can you make sure that treemacs is the latest version? https://github.com/Alexander-Miller/treemacs/blob/17a92097fcd2b5df5d7a8f54e99470ac1168c7bf/src/elisp/treemacs-icons.el#L293

**Comment by mgallego** [comment]
> Can you make sure that treemacs is the latest version? https://github.com/Alexander-Miller/treemacs/blob/17a92097fcd2b5df5d7a8f54e99470ac1168c7bf/src/elisp/treemacs-icons.el#L293

I have the 2.6 version, from Melpa.

**Comment by mgallego** [comment]
Fixed. The version 2.6, the latest in melpa stable dont work. Using the melpa version runs.

Thanks.
