### ISSUE TITLE
(lsp-treemacs-errors-list) and (lsp-treemacs-java-deps-list)  commands displays  a blank buffer

### ISSUE THREAD

**Issue by rmbxz** [emacs-lsp/lsp-treemacs#25]
** Describe the bug **

(lsp-treemacs-errors-list) and (lsp-treemacs-java-deps-list)  commands displays
 a blank buffer inside *LSP Error List*.
 Sometimes it shows a message that there is an error in calling the command :

` ---------------------------------------`
`  It looks like you are trying to run treemacs. Would you like some help with that?`
`  You have called treemacs-mode, but that is just the major mode for treemacs'     `
`  buffers, it is not meant to be used manually.  `
`                                                 `
`  Instead you should call a function like        `
`   * treemacs,                                   `
`   * treemacs-select-window, or                  `
`   * treemacs-add-and-display-current-project    `
`                                                 `
`  You can safely delete this buffer.             `
` ---------------------------------------`
`     \    `
`     \    `
`   ____    `
`   /  \    `
`   |  |    `
`   @  @    `
`   |  |    `
`   || |/    `
`   || ||    `
`   |\_/|    `
`   \___/    `

** To Reproduce **
using treemacs package  treemacs-20191205.557  will produce the above errors 
but the old treemacs package will not produce the above erros.
like using treemacs package           treemacs-20191121.626  will not produce the above errors 

** Expected behavior **
I think the lsp-treemacs should be updated.
because it uses the old version of the treemacs package 

** Logs **
Messages buffer :
[Treemacs] Error on highlight, this shouldn't happen: (wrong-type-argument overlayp nil)

** system **

Linux Debian

GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) 
GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) 
GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11)

lsp-treemacs       20191202.1647 

lsp-java           20191115.1712 
lsp-mode           20191205.1708 
lsp-ui             20191202.2004

**Comment by yyoncho** [comment]
@Alexander-Miller

**Comment by Alexander-Miller** [comment]
Pushed update, things should work again now.

>  Sometimes it shows a message that there is an error in calling the command :

Btw this should not be a message. Clippy is shown in a new buffer when you call treemacs-mode when you meant to use an interactive command like treemacs-select-window.

**Comment by rmbxz** [comment]
after update .
It's working now.  thanks

**Comment by yyoncho** [comment]
@Alexander-Miller thank you!
