### ISSUE TITLE
Add option to close lsp-treemacs buffer on RET action

### ISSUE THREAD

**Issue by ericdallo** [emacs-lsp/lsp-treemacs#34]
When an option from lsp-treemacs is chosen (for example open references file), it does not close the lsp-treemacs buffer, it just goes to the file and keep the buffer open.
Can we add some configuration/option to enable this behavior?

**Comment by nbfalcon** [comment]
After the mentioned PR is merged, the following config snippet will do what you want:
```emacs-lisp
(eval-after-load 'lsp-treemacs          ; `after!' for DOOM
  (add-hook 'lsp-treemacs-after-jump-hook
            (lambda () (kill-buffer lsp-treemacs-symbols-buffer-name))))
```
