### ISSUE TITLE
There is no `lsp-treemacs-symbols-list` function anymore right?

### ISSUE THREAD

**Issue by ccqpein** [emacs-lsp/lsp-treemacs#40]
Hi, I find there is no `lsp-treemacs-symbols-list` in `lsp-treemacs.el`, only has `lsp-treemacs-symbols`. 

However, in README, there is `lsp-treemacs-symbols-list` instead of `lsp-treemacs-symbols`. I guess `lsp-treemacs-symbols-list`is replaced by `lsp-treemacs-symbols`, right?

Thank you.

**Comment by yyoncho** [comment]
sorry for the delayed response, somehow missed that one - it was typo in the readme.
