### ISSUE TITLE
Please consider making a melpa-stable release compatible with lsp-mode 6.3.1

### ISSUE THREAD

**Issue by laurynas-biveinis** [emacs-lsp/lsp-treemacs#49]
The latest lsp-treemacs commits seem to break compatibility with lsp-mode 6.3.1 version:
https://github.com/emacs-lsp/lsp-treemacs/commit/bf054531c278c5d41de504bec3c3df3f2e76c132
https://github.com/emacs-lsp/lsp-treemacs/commit/90754e4189fc78be31f338383db3d8a2042fd8bc

I am only a light lsp-treemacs user so I did not notice the above immediately, but then came along https://github.com/emacs-lsp/lsp-treemacs/commit/5d3f7b49a14b1dd7457c4dcf4233be83b6a4d637, at which point package load broke, presumably due to `lsp-defun` being unavailable.

Maybe tagging last-compatible-with-6.3.1 commit to melpa-stable would be a good idea?

Thanks,

**Comment by yyoncho** [comment]
I tagged https://github.com/emacs-lsp/lsp-treemacs/releases/tag/0.1 (not sure I have picked the correct version).

**Comment by laurynas-biveinis** [comment]
Works in my testing, thank you!
