### ISSUE TITLE
Error list is empty, but error and warning count are correct

### ISSUE THREAD

**Issue by kolemannix** [emacs-lsp/lsp-treemacs#5]
Thank you for this extension, I am very excited to use it!

![image](https://user-images.githubusercontent.com/5499192/58293995-df367d00-7d95-11e9-865b-67ff024d5272.png)

See my issue above. This could be a problem with my configuration but I'm not really sure where to look. I've simply enabled `lsp-treemacs` using `use-package`, as directed:
```
(use-package lsp-treemacs :commands lsp-treemacs-errors-list)
```

I see the correct warning / error count, just not the actual files and errors. Please advise how to debug the issue.

Edit:
Some info: It is a Rust project. I am using treemacs, projectile, lsp-mode, and flycheck, not flymake

**Comment by yyoncho** [comment]
It is a tree, you should be able to expand it using tab/mouse click

**Comment by kolemannix** [comment]
Hah, thanks. You're right, <Tab> works. In my main treemacs window <Enter> is what I use to collapse and expand nodes so I did not even think to try Tab.

Mouse click does nothing
