### ISSUE TITLE
wishlist: support display full function signature 

### ISSUE THREAD

**Issue by Yanhao** [emacs-lsp/lsp-treemacs#60]
Thanks for the excellent work!
Is there any possible to show function signature rather than just function name in lsp-treemacs, or provide an option to control it? I found the signature is more easily to distinguish than only a name.

**Comment by nbfalcon** [comment]
Fixed by #68, which was merged into master; the signature display is on by default.

**Comment by nbfalcon** [comment]
This is should be closed.
