### ISSUE TITLE
Errors list always warns about two errors but never shows them

### ISSUE THREAD

**Issue by ludwj61** [emacs-lsp/lsp-treemacs#65]
![image](https://user-images.githubusercontent.com/42984254/93521533-30a93a80-f8fe-11ea-911a-5dcfa661a29a.png)

This is what I always see on my modeline/when opening lsp-treemacs-error-list. It never shows any errors if I purposefully make them and still shows this empty view if there's no issues.

Also, when I select the folder, for whatever reason it opens dired.

If it matters, I'm using DOOM emacs with java & jdtls.

**Comment by yyoncho** [comment]
Did you try to select that line and press TAB?

**Comment by ludwj61** [comment]
Oh... well that was silly. My mistake, I swear I pressed every other button on my keyboard. Thank you for your quick reply.
