### ISSUE TITLE
Emacs frozens occasionally after call lsp-treemacs-call-hierarchy

### ISSUE THREAD

**Issue by huangfeiyu** [emacs-lsp/lsp-treemacs#72]
I experience this issue occasionally. After I call `lsp-treemacs-call-hierarchy` to try to check the call hierarchy of a method, emacs frozons immediately. When this issue occur, the emacs cpu usage increases to 15% and emacs keeps frozon. I have kill emacs manually. My emacs version is 26.1 the version with the debian 10. Thanks!

**Comment by nbfalcon** [comment]
Does `C-g` work? That function calls `lsp-request`, which works synchronously. If your language server takes a long time to respond, Emacs will appear stuck.

**Comment by huangfeiyu** [comment]
C-g doesn't work, neither ESC-ESC-ESC, I have to kill emacs and lsp server manually. Can setting a timeout help? The issue occur occasionally.

**Comment by yyoncho** [comment]
have you tried to kill the language server?

**Comment by huangfeiyu** [comment]
Yes, I tried to kill language server by using task manager. And after the server killed, emacs remains freeze.

**Comment by SreenivasVRao** [comment]
Same behaviour seen with lsp-treemacs-references. I get "Refresh Completed" in the echo area and then emacs completely hangs. Have to force quit.

**Comment by huangfeiyu** [comment]
The Issue may has something to do with Wind Move mode https://www.emacswiki.org/emacs/WindMove. Sometimes I experience the issue when I use Wind Move mode to switch to the hierarchy window, but if I use other-window command, it works fine.

**Comment by yyoncho** [comment]
I think that the root cause was fixed as part of https://github.com/emacs-lsp/lsp-treemacs/commit/642e922e16fd2b2c3cc075d7cba68448f1aaa006 please reopen if you still lsee it.

**Comment by huangfeiyu** [comment]
Great! @yyoncho thanks!
