### ISSUE TITLE
lsp-treemacs not working

### ISSUE THREAD

**Issue by BonZai-841** [emacs-lsp/lsp-treemacs#80]
I am using doom emacs and I install lsp-treemacs using M-x Package-install

after running lsp-treemacs-symbols or any other lsp-treemacs app it gives me this error `Error processing message (void-function lsp-render-symbol).`

**Comment by jcs090218** [comment]
Hmm... This doesn't seems right. The function `lsp-render-symbol` defined in `lsp-mode` and then this package included `lsp-mode` at the very top of the file. 😕

**Comment by leungbk** [comment]
Doom has its own way of managing packages, using Straight.el.

> WARNING: Do not install packages directly (with M-x package-install or M-x straight-use-package). Without an accompanying package! declaration somewhere these packages will be forgotten when you restart Emacs and uninstalled the next time you run doom sync or doom purge.

You should install using Doom's `package!` macro.

**Comment by BonZai-841** [comment]
> Doom has its own way of managing packages, using Straight.el.
> 
> > WARNING: Do not install packages directly (with M-x package-install or M-x straight-use-package). Without an accompanying package! declaration somewhere these packages will be forgotten when you restart Emacs and uninstalled the next time you run doom sync or doom purge.
> 
> You should install using Doom's `package!` macro.

Oh thank you! it worked after using this code in ~/.doom.d/packages.el `(package! lsp-treemacs)`
